name: Test All Branches 1
run-name: Run on branch ${{ github.ref }}
on: [push]
jobs:
  Test-All-Branches-Action-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
